package com.capsconc.arcshield.schema.ciaer

/**
 * Phase 4 hook — structural isolation of generated CIAER+ events (CLAUDE.md §7).
 *
 * Reserved at schema level now so partitioning constraints are baked in before
 * any synthetic data enters the corpus. SYNTHETIC_* chains that diverge from the
 * executed human action are classified INDETERMINATE and partitioned into Q' —
 * they never update C (OGC firewall, CLAUDE.md §6).
 *
 *   HUMAN              → executed by a human operator; eligible for C update on R_phys arrival
 *   SYNTHETIC_LLM      → generated by Twin/RAG/LLM; held in Q' until validated by R_phys
 *   SYNTHETIC_CODEBOOK → generated by codebook matcher; held in Q' until validated
 */
enum class ProvenanceClass {
    HUMAN,
    SYNTHETIC_LLM,
    SYNTHETIC_CODEBOOK,
}

/**
 * Phase 4 hook — execution-time lock for synthetic predictions.
 *
 * [sealTimestampNanos] is the elapsedRealtimeNanos at which the synthetic prediction
 * was registered. It must be strictly before the physical outcome resolves (R_phys
 * arrival). Records without a seal cannot be used for confidence calibration.
 *
 * For HUMAN events this field is null — the operator's action timestamp serves as
 * the implicit seal.
 */
data class SealedProvenanceTag(
    val provenanceClass:    ProvenanceClass,
    val syntheticOperatorId: String?,         // e.g. "synth-claude", "synth-rag-twin"; null for HUMAN
    val sealTimestampNanos: Long?,            // null for HUMAN
)
